/**
CREATE TABLE T_RC_FILEENTITY (
  nr_idFile         INTEGER NOT NULL,
  txt_fileName      VARCHAR(50) NOT NULL,
  txt_fileUrl       VARCHAR(100) NOT NULL,
  nr_size           INTEGER NOT NULL,
  txt_contentType   VARCHAR(15) NOT NULL,
  txt_sheetData     BYTEA NOT NULL,
  
  PRIMARY KEY (nr_idFile)
);

ALTER TABLE T_RC_FILEENTITY ADD dt_timeNDate DATE;
ALTER TABLE dt_timeNDate MODIFY TIMESTAMP WITHOUT TIME ZONE; 

CREATE TABLE T_RC_USERS (
	nr_id	INTEGER NOT NULL,
	txt_email	VARCHAR(50) NOT NULL;
	txt_password	VARCHAR(100) NOT NULL;
	
  PRIMARY KEY (nr_id)
);

CREATE TABLE T_RC_USERS_FILES (
	id_user	INTEGER,
	id_file	UUID,
	
  PRIMARY KEY (id_user, id_file),
  FOREIGN KEY (id_user) REFERENCES T_RC_USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (id_file) REFERENCES T_RC_FILEENTITY(id)
);

INSERT INTO T_RC_USERS_FILES(id_user, id_file) VALUES 
(7, (SELECT id FROM T_RC_FILEENTITY WHERE id = '04750b47-58e0-4b8d-a30e-7d472dcef5a2'))*/
